version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - noctx
    - prealloc
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    govet:
      disable:
        - fieldalignment
    misspell:
      locale: US
    gosec:
      excludes:
        - G104 # Audit errors not checked
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: 
        - github.com/spagu/docker-stats

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
